feat(esx_mechanicjob) General Improvements
esx-framework/esx_mechanicjob pull request #15
Opened 2023-06-29 08:33 UTC by thesysadmindev

- Added ability to disable NPC jobs.
- Added exploit protection checks to:
  - Harvesting gas bottles,
  - Harvesting repair tools,
  - Harvesting body repair tools,
  - Crafting blowtorches,
  - Crafting repair kits,
  - Crafting body repair kits,
  - NPC job completion, and
  - Withdrawing items from the society inventory.

2023-06-29 09:22 UTC, Cyzxin commented on server/main.lua
> +		print('[^3WARNING^7] Player ^5' .. xPlayer.getIdentifier() .. '^7 attempted to harvest gas bottles without the Mechanic job!')
I'm pretty sure using formatting on strings rather than concatenation is preferred. Other than that seems like a big improvement!

2023-06-29 12:04 UTC, thesysadmindev commented on server/main.lua
> +		print('[^3WARNING^7] Player ^5' .. xPlayer.getIdentifier() .. '^7 attempted to harvest gas bottles without the Mechanic job!')
I've updated the prints, thanks for the tip!

2023-07-21 00:40 UTC, Gellipapa commented
@thesysadmindev @Cyzxin What a status? Please tell me.

2023-08-20 11:36 UTC, Gellipapa requested changes
Please read my comments and fix issues.

2023-08-20 11:36 UTC, Gellipapa commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Please reverse the condition
```lua
if xPlayer.job.name ~= 'mechanic' then
   print(('[^3WARNING^7] Player ^5"%s"^7 attempted to harvest gas bottles without the Mechanic job!'):format(getIdent))
   return
end

PlayersHarvesting[source] = true
TriggerClientEvent('esx:showNotification', source, TranslateCap('recovery_gas_can'))
Harvest(source)
```

2023-08-20 11:36 UTC, Gellipapa commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Please reverse the condition.

2023-08-20 11:36 UTC, Gellipapa commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Please reverse the condition

2023-08-20 11:36 UTC, Gellipapa commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Please reverse the condition

2023-08-20 11:36 UTC, Gellipapa commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Please reverse the condition

2023-08-20 11:36 UTC, Gellipapa commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Please reverse the condition

2023-08-20 11:36 UTC, Gellipapa commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Please reverse the condition

2023-08-20 11:36 UTC, Gellipapa commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Please reverse the condition

2023-08-20 11:36 UTC, Gellipapa commented on config.lua
> +Config.EnableNPCJobs			  = true
fix format please

2023-08-20 11:36 UTC, Gellipapa commented on client/main.lua
> +	RegisterKeyMapping('mechanicjob', 'Togggle NPC Job', 'keyboard', 'F6')
F6 is open mechanic menu, i think you should add other key and maybe add than config value.

2023-08-20 11:39 UTC, Gellipapa commented
A suggestion is to write a method to check if the player's work is the mechanic and if not to display the corresponding warning error, say in a parameter you can pass which one.

For example: 

```lua
function hasMechanicJob(craftItemName)
  if not mechanic then
     print(("warnd %s"):format(craftItemName)) 
      return false
  end
  return true
end
```

2023-10-17 05:59 UTC, thesysadmindev commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Condition has been reversed.

2023-10-17 05:59 UTC, thesysadmindev commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Condition has been reversed.

2023-10-17 05:59 UTC, thesysadmindev commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Condition has been reversed.

2023-10-17 05:59 UTC, thesysadmindev commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Condition has been reversed.

2023-10-17 05:59 UTC, thesysadmindev commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Condition has been reversed.

2023-10-17 05:59 UTC, thesysadmindev commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Condition has been reversed.

2023-10-17 06:00 UTC, thesysadmindev commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Condition has been reversed.

2023-10-17 06:00 UTC, thesysadmindev commented on server/main.lua
> +	if xPlayer.job.name == 'mechanic' then
Condition has been reversed.

2023-10-17 06:00 UTC, thesysadmindev commented on client/main.lua
> +	RegisterKeyMapping('mechanicjob', 'Togggle NPC Job', 'keyboard', 'F6')
I've replaced F6 with F5, and added config options for both Toggle NPC Job and Open Mechanic Menu.

2023-10-17 06:01 UTC, thesysadmindev commented on config.lua
> +Config.EnableNPCJobs			  = true
Formatting has been fixed.

2023-10-18 05:46 UTC, thesysadmindev reviewed
All required changes have been made.

2023-12-12 09:43 UTC, closed without merging